require('nvim-treesitter.configs').setup({
  auto_install = true,
  ensure_installed = {
    'bash',
    'c',
    'dockerfile',
    'dot',
    'git_config',
    'git_rebase',
    'hcl',
    'java',
    'json',
    'lua',
    'make',
    'markdown',
    'markdown_inline',
    'python',
    'rst',
    'rust',
    'terraform',
    'toml',
    'vim',
    'vimdoc',
    'yaml',
  },
})
